In [1]:
import sys, os
notebook_dir = os.path.dirname(os.path.abspath("__file__"))
sys.path+=[notebook_dir+'\\engine']

In [35]:
from torchengine import AnalyticalSet, EliminateAnalysis
from torchdata import generate_indices
import torch

In [5]:
indices = generate_indices(['a','b','x','y','z'])

In [12]:
x0 = torch.ones(5, dtype=torch.float64)

### One n=3 discipline

In [47]:
def full_discipline(a,b):
    x = a+b     # a+b-x   =0
    z = a-b     # a-b-z   =0
    y = x**2+z  # x^2+z-y =0
    return x,y,z

S1 = AnalyticalSet((('a','b'), ('x','y','z'), full_discipline), indices)

In [48]:
S1.analysis(x0)

tensor([1., 1., 2., 4., 0.], dtype=torch.float64)

### n=2 + n=1 discipline

In [49]:
A2 = AnalyticalSet((('a','b'), ('x','z'), lambda a,b: [a+b,a-b]), indices)
A1 = AnalyticalSet((('x','z'), ('y',), lambda x,z: x**2+z), indices)
S2 = EliminateAnalysis([A2.analysis, A1.analysis])

In [50]:
S2(x0)

tensor([1., 1., 2., 4., 0.], dtype=torch.float64)

### Three n=1 disciplines

In [51]:
A1 = AnalyticalSet((('a','b'), ('x',), lambda a,b: a+b), indices)
A2 = AnalyticalSet((('a','b'), ('z',), lambda a,b: a-b), indices)
A3 = AnalyticalSet((('x','z'), ('y',), lambda x,z: x**2+z), indices)
S3 = EliminateAnalysis([A1.analysis, A2.analysis, A3.analysis])

In [52]:
S3(x0)

tensor([1., 1., 2., 4., 0.], dtype=torch.float64)